apiVersion: apps/v1
kind: Deployment
metadata:
  name: operator
  namespace: system
  labels:
    control-plane: controller-manager
spec:
  selector:
    matchLabels:
      control-plane: controller-manager
  replicas: 1
  template:
    metadata:
      labels:
        control-plane: controller-manager
    spec:
      serviceAccountName: notification-manager-sa
      containers:
      - command:
        - /notification-manager-operator
        args:
        - --enable-leader-election
        image: controller:v0.6.0
        imagePullPolicy: IfNotPresent
        name: notification-manager-operator
        resources:
          limits:
            cpu: 100m
            memory: 30Mi
          requests:
            cpu: 100m
            memory: 20Mi
        volumeMounts:
          - mountPath: /etc/localtime
            name: host-time
      volumes:
        - hostPath:
            path: /etc/localtime
            type: ""
          name: host-time
      terminationGracePeriodSeconds: 10
