apiVersion: v1
kind: ServiceAccount
metadata:
  name: notification-manager-sa
  namespace: {{ include "nm.namespaceOverride" . }}
{{- with .Values.global.imagePullSecrets }}
imagePullSecrets:
  {{- toYaml . | nindent 2 }}
{{- end }}
