apiVersion: notification.kubesphere.io/v1alpha1
kind: SlackConfig
metadata:
  name: default-slack-config
  labels:
    type: default
spec:
  slackTokenSecret:
    key: token
    name: slack-token-secret
  httpConfigSelector:
    matchLabels:
      type: tenant
      user: admin