#
# Copyright 2022 The Notification-Manager Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

name: WorkFlow for Building sidecar image

on:
  push:
    branches:
      - 'master'
    paths:
      - '.github/workflows/push-sidecar-image.yaml'
      - 'sidecar/kubesphere/4.0.0/backend.go'
      - 'sidecar/kubesphere/4.0.0/Dockerfile'
      - 'sidecar/kubesphere/4.0.0/main.go'
      - 'sidecar/kubesphere/4.0.0/Makefile'
      - 'sidecar/kubesphere/4.0.0/go.sum'
      - 'sidecar/kubesphere/4.0.0/go.mod'

env:
  REPO_OP: 'kubesphere'

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    name: Build Operator Image
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.20.x

      - uses: actions/cache@v3
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}

      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up QEMU
        id: qemu
        uses: docker/setup-qemu-action@v1
        with:
          image: tonistiigi/binfmt:latest
          platforms: all

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and Push image
        run: |
          cd sidecar/kubesphere/4.0.0 && make